name: 6 Hours Mass Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 20 параллельных машин
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false
    
    # Ставим общий лимит времени для джобы (чуть меньше 6 часов, чтобы успеть сохраниться)
    timeout-minutes: 355 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Program for 6 Hours
        run: |
          chmod +x ./virus
          echo "Запуск машины №${{ matrix.machine }}"
          
          # Запускаем программу на 5 часов 50 минут (350 минут)
          # Чтобы GitHub не убил её раньше времени как "orphan", 
          # мы запускаем её прямо или через команду timeout.
          timeout 350m ./virus || echo "Программа завершила работу или вышло время"
